"""contacts

Revision ID: 106c4fb48010
Revises: b739489ebbe4
Create Date: 2025-10-22 12:19:33.239671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '106c4fb48010'
down_revision: Union[str, Sequence[str], None] = 'b739489ebbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('type', sa.Enum('customer', 'supplier', 'both', name='contacts_type_enum'), server_default='customer', nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_gstin'), 'contacts', ['gstin'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.drop_table('migrations')
    op.drop_index(op.f('IDX_3167e70217fbe27dcf0f93164e'), table_name='containers')
    op.drop_table('containers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('containers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('single', 'mixed', name='containers_type_enum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_21cbac3e68f7b1cf53d39cda70c')),
    sa.UniqueConstraint('name', name=op.f('UQ_3167e70217fbe27dcf0f93164ed'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('IDX_3167e70217fbe27dcf0f93164e'), 'containers', ['name'], unique=False)
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_8c82d7f526340ab734260ea46be'))
    )
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_gstin'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
