"""transactions invoices

Revision ID: 599c24b19b1e
Revises: bf5a4949ff19
Create Date: 2025-10-26 13:30:58.445475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599c24b19b1e'
down_revision: Union[str, Sequence[str], None] = 'bf5a4949ff19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('invoice_url', sa.String(length=500), nullable=True))
    op.add_column('transactions', sa.Column('invoice_checksum', sa.String(length=64), nullable=True))
    op.create_index('idx_transaction_invoice_url', 'transactions', ['invoice_url'], unique=False)
    op.create_index(op.f('ix_transactions_invoice_url'), 'transactions', ['invoice_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_invoice_url'), table_name='transactions')
    op.drop_index('idx_transaction_invoice_url', table_name='transactions')
    op.drop_column('transactions', 'invoice_checksum')
    op.drop_column('transactions', 'invoice_url')
    # ### end Alembic commands ###
