"""move-py

Revision ID: b739489ebbe4
Revises: 
Create Date: 2025-10-21 19:21:53.697161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b739489ebbe4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Keep TypeORM tables (migrations, containers) - they're managed by TypeORM
    op.drop_index(op.f('IDX_14f850c34e63edcdfd0aa66d31'), table_name='container')
    op.drop_constraint(op.f('UQ_14f850c34e63edcdfd0aa66d316'), 'container', type_='unique')
    op.create_index(op.f('ix_container_name'), 'container', ['name'], unique=True)
    # Rename containerId -> container_id and productId -> product_id with data migration
    # Step 1: Add new columns as nullable
    op.add_column('container_product', sa.Column('container_id', sa.Integer(), nullable=True))
    op.add_column('container_product', sa.Column('product_id', sa.Integer(), nullable=True))
    
    # Step 2: Copy data from old columns to new columns
    op.execute('UPDATE container_product SET container_id = "containerId", product_id = "productId"')
    
    # Step 3: Make new columns NOT NULL
    op.alter_column('container_product', 'container_id', nullable=False)
    op.alter_column('container_product', 'product_id', nullable=False)
    
    # Step 4: Drop old constraints and indexes
    op.drop_index(op.f('IDX_96fdb3f2b800da62b0d8cbff44'), table_name='container_product')
    op.drop_constraint(op.f('FK_c97f9c07a693f8928723456e1e3'), 'container_product', type_='foreignkey')
    op.drop_constraint(op.f('FK_06838bb77c244e2f78636380d9c'), 'container_product', type_='foreignkey')
    
    # Step 5: Create new indexes and constraints
    op.create_index('idx_container_product_unique', 'container_product', ['container_id', 'product_id'], unique=True)
    op.create_foreign_key('fk_container_product_product_id', 'container_product', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_container_product_container_id', 'container_product', 'container', ['container_id'], ['id'], ondelete='CASCADE')
    
    # Step 6: Drop old columns
    op.drop_column('container_product', 'productId')
    op.drop_column('container_product', 'containerId')
    # Rename containerId -> container_id and productId -> product_id with data migration
    # Step 1: Add new columns as nullable
    op.add_column('inventory_log', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('inventory_log', sa.Column('container_id', sa.Integer(), nullable=True))
    
    # Step 2: Copy data from old columns to new columns
    op.execute('UPDATE inventory_log SET container_id = "containerId", product_id = "productId"')
    
    # Step 3: Make new columns NOT NULL
    op.alter_column('inventory_log', 'container_id', nullable=False)
    op.alter_column('inventory_log', 'product_id', nullable=False)
    
    # Step 4: Drop old constraints
    op.drop_constraint(op.f('FK_7878b93342d306307315e2acfdb'), 'inventory_log', type_='foreignkey')
    op.drop_constraint(op.f('FK_4cad699a602ac52c29fa27e5d8f'), 'inventory_log', type_='foreignkey')
    
    # Step 5: Create new constraints
    op.create_foreign_key('fk_inventory_log_product_id', 'inventory_log', 'product', ['product_id'], ['id'])
    op.create_foreign_key('fk_inventory_log_container_id', 'inventory_log', 'container', ['container_id'], ['id'])
    
    # Step 6: Drop old columns
    op.drop_column('inventory_log', 'containerId')
    op.drop_column('inventory_log', 'productId')
    op.drop_index(op.f('IDX_0d60a373cfcce8f2e05243df45'), table_name='product')
    op.create_index('idx_product_name_size_packing', 'product', ['name', 'size', 'packing'], unique=True)
    op.drop_constraint(op.f('UQ_fe0bb3f6520ee0469504521e710'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('UQ_fe0bb3f6520ee0469504521e710'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_product_name_size_packing', table_name='product')
    op.create_index(op.f('IDX_0d60a373cfcce8f2e05243df45'), 'product', ['name', 'size', 'packing'], unique=True)
    op.add_column('inventory_log', sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('inventory_log', sa.Column('containerId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_inventory_log_container_id', 'inventory_log', type_='foreignkey')
    op.drop_constraint('fk_inventory_log_product_id', 'inventory_log', type_='foreignkey')
    op.create_foreign_key(op.f('FK_4cad699a602ac52c29fa27e5d8f'), 'inventory_log', 'container', ['containerId'], ['id'])
    op.create_foreign_key(op.f('FK_7878b93342d306307315e2acfdb'), 'inventory_log', 'product', ['productId'], ['id'])
    op.drop_column('inventory_log', 'container_id')
    op.drop_column('inventory_log', 'product_id')
    op.add_column('container_product', sa.Column('containerId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('container_product', sa.Column('productId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_container_product_container_id', 'container_product', type_='foreignkey')
    op.drop_constraint('fk_container_product_product_id', 'container_product', type_='foreignkey')
    op.create_foreign_key(op.f('FK_06838bb77c244e2f78636380d9c'), 'container_product', 'product', ['productId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('FK_c97f9c07a693f8928723456e1e3'), 'container_product', 'container', ['containerId'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_container_product_unique', table_name='container_product')
    op.create_index(op.f('IDX_96fdb3f2b800da62b0d8cbff44'), 'container_product', ['containerId', 'productId'], unique=True)
    op.drop_column('container_product', 'product_id')
    op.drop_column('container_product', 'container_id')
    op.drop_index(op.f('ix_container_name'), table_name='container')
    op.create_unique_constraint(op.f('UQ_14f850c34e63edcdfd0aa66d316'), 'container', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('IDX_14f850c34e63edcdfd0aa66d31'), 'container', ['name'], unique=False)
    # Don't recreate TypeORM tables (migrations, containers) - they're managed by TypeORM
    # ### end Alembic commands ###
