"""transactions

Revision ID: bf5a4949ff19
Revises: 106c4fb48010
Create Date: 2025-10-23 01:34:57.720706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5a4949ff19'
down_revision: Union[str, Sequence[str], None] = '106c4fb48010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_number', sa.String(length=50), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('sale', 'purchase', name='transaction_type_enum'), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('payment_status', sa.Enum('paid', 'partial', 'unpaid', name='payment_status_enum'), server_default='unpaid', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='fk_transaction_contact_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_contact_id', 'transactions', ['contact_id'], unique=False)
    op.create_index('idx_transaction_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('idx_transaction_number', 'transactions', ['transaction_number'], unique=True)
    op.create_index('idx_transaction_type_status', 'transactions', ['type', 'payment_status'], unique=False)
    op.create_index(op.f('ix_transactions_contact_id'), 'transactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_number'), 'transactions', ['transaction_number'], unique=True)
    op.create_table('payments',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'upi', 'cheque', 'other', name='payment_method_enum'), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_payment_transaction_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_index('idx_payment_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.create_table('transaction_items',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], name='fk_transaction_item_container_id'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_transaction_item_product_id'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='fk_transaction_item_transaction_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_item_product_id', 'transaction_items', ['product_id'], unique=False)
    op.create_index('idx_transaction_item_transaction_id', 'transaction_items', ['transaction_id'], unique=False)
    op.create_index('idx_transaction_item_transaction_product', 'transaction_items', ['transaction_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_product_id'), 'transaction_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    op.add_column('product', sa.Column('default_sale_price', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('product', sa.Column('default_purchase_price', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'default_purchase_price')
    op.drop_column('product', 'default_sale_price')
    op.drop_index(op.f('ix_transaction_items_transaction_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_product_id'), table_name='transaction_items')
    op.drop_index('idx_transaction_item_transaction_product', table_name='transaction_items')
    op.drop_index('idx_transaction_item_transaction_id', table_name='transaction_items')
    op.drop_index('idx_transaction_item_product_id', table_name='transaction_items')
    op.drop_table('transaction_items')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index('idx_payment_transaction_id', table_name='payments')
    op.drop_index('idx_payment_date', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_transactions_transaction_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_contact_id'), table_name='transactions')
    op.drop_index('idx_transaction_type_status', table_name='transactions')
    op.drop_index('idx_transaction_number', table_name='transactions')
    op.drop_index('idx_transaction_date', table_name='transactions')
    op.drop_index('idx_transaction_contact_id', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
