"""transactions payments

Revision ID: c1e5908552a3
Revises: 599c24b19b1e
Create Date: 2025-10-26 18:31:11.546396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e5908552a3'
down_revision: Union[str, Sequence[str], None] = '599c24b19b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('description', sa.String(length=500), nullable=True))
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_payment_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.create_index('idx_payment_category', 'payments', ['category'], unique=False)
    op.create_index(op.f('ix_payments_category'), 'payments', ['category'], unique=False)
    op.create_foreign_key('fk_payment_contact_id', 'payments', 'contacts', ['contact_id'], ['id'])
    op.drop_index(op.f('idx_transaction_item_product_id'), table_name='transaction_items')
    op.drop_index(op.f('idx_transaction_item_transaction_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_product_id'), table_name='transaction_items')
    op.drop_index(op.f('ix_transaction_items_transaction_id'), table_name='transaction_items')
    op.drop_index(op.f('idx_transaction_contact_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_contact_id'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_contact_id'), 'transactions', ['contact_id'], unique=False)
    op.create_index(op.f('idx_transaction_contact_id'), 'transactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_items_product_id'), 'transaction_items', ['product_id'], unique=False)
    op.create_index(op.f('idx_transaction_item_transaction_id'), 'transaction_items', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_transaction_item_product_id'), 'transaction_items', ['product_id'], unique=False)
    op.drop_constraint('fk_payment_contact_id', 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_category'), table_name='payments')
    op.drop_index('idx_payment_category', table_name='payments')
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.create_index(op.f('idx_payment_transaction_id'), 'payments', ['transaction_id'], unique=False)
    op.alter_column('payments', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'description')
    op.drop_column('payments', 'category')
    op.drop_column('payments', 'contact_id')
    # ### end Alembic commands ###
