"""payments

Revision ID: db28b9766f37
Revises: c1e5908552a3
Create Date: 2025-10-29 00:49:29.092542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db28b9766f37'
down_revision: Union[str, Sequence[str], None] = 'c1e5908552a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('type', sa.String(length=16), server_default='expense', nullable=False))
    op.drop_index(op.f('idx_payment_category'), table_name='payments')
    op.drop_index(op.f('idx_payment_date'), table_name='payments')
    op.create_index('idx_payment_type', 'payments', ['type'], unique=False)
    op.create_index(op.f('ix_payments_type'), 'payments', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_type'), table_name='payments')
    op.drop_index('idx_payment_type', table_name='payments')
    op.create_index(op.f('idx_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('idx_payment_category'), 'payments', ['category'], unique=False)
    op.drop_column('payments', 'type')
    # ### end Alembic commands ###
